### PR TITLE
Add ESP32 example

### PR DESCRIPTION
**Pull request by bertmelis**
- add esp32 example
- merge library.json files

### CODE REVIEW

**Comment by bertmelis** [comment]
don't know how to integrate the example in Travis CI though

**Comment by timpur** [comment]
beyond me @marvinroger?

**Comment by marvinroger** [comment]
@bertmelis @timpur take a look at this:

```yaml
language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/TimeArduinoDue PLATFORMIO_CI_EXTRA_ARGS="--board=due"
    - PLATFORMIO_CI_SRC=examples/TimeGPS
    - PLATFORMIO_CI_SRC=examples/TimeNTP
    - PLATFORMIO_CI_SRC=examples/TimeTeensy3 PLATFORMIO_CI_EXTRA_ARGS="--board=teensy31"
    # - ...

install:
    - pip install -U platformio
    - rm -rf ./linux

    #
    # Libraries from PlatformIO Library Registry:
    #
    # http://platformio.org/lib/show/416/TinyGPS
    - platformio lib -g install 416 421 422

script:
    - platformio ci --lib="." --board=uno --board=teensy20pp $PLATFORMIO_CI_EXTRA_ARGS
```

So basically, add a `PLATFORMIO_CI_EXTRA_ARGS` env variable with the args you want (so compile on esp8266 for the main example and esp32 for the esp32 example) and append this env variable to the script. 😉

**Comment by marvinroger** [comment]
@timpur feel free to PR again the upstream repo when this is merged

**Comment by timpur** [comment]
Thanks @marvinroger 
@bertmelis can you make the relevant changes then ill merge a push to up stream

**Comment by marvinroger** [comment]
@bertmelis that's overly complicated :)

```yaml
language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/FullyFeatured/FullyFeatured.ino PLATFORMIO_CI_EXTRA_ARGS="--board=esp01 --board=nodemcuv2"
    - PLATFORMIO_CI_SRC=examples/FullyFeatured-ESP32/FullyFeatured-ESP32.ino PLATFORMIO_CI_EXTRA_ARGS="--board=lolin32"
    - CPPLINT=TRUE

install:
    - pip install -U platformio
    - pip install cpplint
    - platformio lib -g install file://.

script:
    - if [[ "$CPPLINT" ]]; then make cpplint; else platformio ci $PLATFORMIO_CI_EXTRA_ARGS; fi
```

**Comment by bertmelis** [comment]
I'm going to close this PR and do some research on Travis CI. The library dependencies are something I haven't got in my fingers. Will come back when it's working.

I should have created a branch to test...

**Comment by timpur** [comment]
Yeah soz 
I don't know platformIO

**Pull request closed without merging**
